module.exports = function(sequelize, DataTypes) {
    const Move = sequelize.define("Move", {
        // (Mover is technically contained in PieceId generated by Sequelize:)
        mover: DataTypes.ENUM("Dad", "Me"),
        startRow: {
            type: DataTypes.INTEGER,
            allowNull: false
        },
        startColumn: {
            type: DataTypes.INTEGER,
            allowNull: false
        },
        destinationRow: {
            type: DataTypes.INTEGER,
            allowNull: false
        },
        destinationColumn: {
            type: DataTypes.INTEGER,
            allowNull: false
        },
        pieceTaken: DataTypes.BOOLEAN,
        createdAt: {
            type: DataTypes.DATE,
            allowNull: false,
            defaultValue: sequelize.fn('NOW')
        },
        updatedAt: {
            type: DataTypes.DATE,
            allowNull: false,
            defaultValue: sequelize.fn('NOW')
        }
    });

    Move.associate = function(models) {
        // Move cannot be made without its Game
        Move.belongsTo(models.Game, {
            foreignKey: {
                allowNull: false
            }
        });
        // Move always has only one Piece
        Move.belongsTo(models.Piece, {
            foreignKey: {
                allowNull: false
            }
        });
        // Move can have only one PieceTaken
        Move.belongsTo(models.Piece, {
            as: "PieceTaken"
        });
    };

    return Move;
};
